name: Amalgamate Pages
description: Amalgamate builds from many branches into one GitHub Pages site
inputs:
  workflow_name:
    description: Name of the workflow that produces artifacts for each branch
    required: true
  artifact_name:
    description: Name of the artifact produced by the workflow
    required: true
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        cache-dependency-glob: |
          ${{ github.action_path }}/pyproject.toml
          ${{ github.action_path }}/uv.lock
        ignore-empty-workdir: true
        working-directory: "${{ github.action_path }}"

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Assemble site from all live branches
      id: assemble
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        uv run --frozen godoctopus.py amalgamate
      env:
        DEBUG: ${{ runner.debug }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.assemble.outputs.path }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

    - name: Update build statuses
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        uv run --frozen godoctopus.py update-status
      env:
        DEBUG: ${{ runner.debug }}
        GITHUB_TOKEN: ${{ github.token }}
